#####  Valore del pinCode per l'accesso ai servizi CIL
config.ws.target.cil.pinCode=${config.ws.target.cil.pinCode}

##### Attiva emulazione CIL
config.ws.target.cil.emulation=${config.ws.target.cil.emulation}

##### Chiavi Credenziali SAR su DB Areas
# se TRUE abilita la ricerca chiavi sulla SI_KEYRAD
config.ws.target.sar.credential.db.load=${config.ws.target.sar.credential.db.load}
config.ws.target.sar.credential.db.key.pinCode=${config.ws.target.sar.credential.db.key.pinCode}
config.ws.target.sar.credential.db.key.userName=${config.ws.target.sar.credential.db.key.userName}
config.ws.target.sar.credential.db.key.pwd=${config.ws.target.sar.credential.db.key.pwd}

##### Attiva il monitoraggio per la reportistica
config.ws.service.monitoring=${config.ws.service.monitoring}
#Salva solo i messaggi verso il SAR escludendo i messaggi interni
config.ws.service.monitoring.internalmsgs=${config.ws.service.monitoring.internalmsgs}

#####  Servizio CIL RichiestaNreService: operation da richiamare
config.ws.target.cil.richiestaNre.operationName=richiestaNre
#####  Servizio CIL RichiestaNreService: nome del servizio
config.ws.target.cil.richiestaNre.serviceName=richiestaNreImplService
#####  Servizio CIL RichiestaNreService: endpoint del servizio
config.ws.target.cil.richiestaNre.serviceEndpoint=${config.ws.target.cil.richiestaNre.serviceEndpoint}
#####  Servizio CIL RichiestaNreService: id della configurazione di Rampart (default se non utilizzato WS-Security)
config.ws.target.cil.richiestaNre.securityConfigId=default
#####  Servizio CIL RichiestaNreService: overriding delle proprietà di configurazione del client
config.ws.target.cil.richiestaNre.customProp.config.ws.client.timeout=${config.ws.client.timeout}
config.ws.target.cil.richiestaNre.customProp.config.ws.client.so.timeout=${config.ws.client.so.timeout}

#####  Servizio CIL DemInvioPrescrittoService: operation da richiamare
config.ws.target.cil.demInvioPrescritto.operationName=invioPrescritto
#####  Servizio CIL DemInvioPrescrittoService: nome del servizio
config.ws.target.cil.demInvioPrescritto.serviceName=demInvioPrescritto
#####  Servizio CIL DemInvioPrescrittoService: endpoint del servizio
config.ws.target.cil.demInvioPrescritto.serviceEndpoint=${config.ws.target.cil.demInvioPrescritto.serviceEndpoint}
#####  Servizio CIL DemInvioPrescrittoService: id della configurazione di Rampart (default se non utilizzato WS-Security)
config.ws.target.cil.demInvioPrescritto.securityConfigId=default
#####  Servizio CIL DemInvioPrescrittoService: overriding delle proprietà di configurazione del client
config.ws.target.cil.demInvioPrescritto.customProp.config.ws.client.timeout=${config.ws.client.timeout}
onfig.ws.target.cil.demInvioPrescritto.customProp.config.ws.client.so.timeout=${config.ws.client.so.timeout}

#####  Servizio CIL DemAnnullaPrescrittoService: operation da richiamare
config.ws.target.cil.demAnnullaPrescritto.operationName=annullaPrescritto
#####  Servizio CIL DemAnnullaPrescrittoService: nome del servizio
config.ws.target.cil.demAnnullaPrescritto.serviceName=demAnnullaPrescritto
#####  Servizio CIL DemAnnullaPrescrittoService: endpoint del servizio
config.ws.target.cil.demAnnullaPrescritto.serviceEndpoint=${config.ws.target.cil.demAnnullaPrescritto.serviceEndpoint}
#####  Servizio CIL DemAnnullaPrescrittoService: id della configurazione di Rampart (default se non utilizzato WS-Security)
config.ws.target.cil.demAnnullaPrescritto.securityConfigId=default
#####  Servizio CIL DemAnnullaPrescrittoService: overriding delle proprietà di configurazione del client
config.ws.target.cil.demAnnullaPrescritto.customProp.config.ws.client.timeout=${config.ws.client.timeout}
config.ws.target.cil.demAnnullaPrescritto.customProp.config.ws.client.so.timeout=${config.ws.client.so.timeout}

#####  Servizio CIL DemVisualizzaPrescrittoService: operation da richiamare
config.ws.target.cil.demVisualizzaPrescritto.operationName=visualizzaPrescritto
#####  Servizio CIL DemVisualizzaPrescrittoService: nome del servizio
config.ws.target.cil.demVisualizzaPrescritto.serviceName=demVisualizzaPrescritto
#####  Servizio CIL DemVisualizzaPrescrittoService: endpoint del servizio
config.ws.target.cil.demVisualizzaPrescritto.serviceEndpoint=${config.ws.target.cil.demVisualizzaPrescritto.serviceEndpoint}
#####  Servizio CIL DemVisualizzaPrescrittoService: id della configurazione di Rampart (default se non utilizzato WS-Security)
config.ws.target.cil.demVisualizzaPrescritto.securityConfigId=default
#####  Servizio CIL DemVisualizzaPrescrittoService: overriding delle proprietà di configurazione del client
config.ws.target.cil.demVisualizzaPrescritto.customProp.config.ws.client.timeout=${config.ws.client.timeout}
config.ws.target.cil.demVisualizzaPrescritto.customProp.config.ws.client.so.timeout=${config.ws.client.so.timeout}

#####  Servizio CIL InvioTelematicoSanitaService: operation da richiamare
config.ws.target.cil.invioTelematicoSanita.operationName=inviaFileSanita
#####  Servizio CIL InvioTelematicoSanitaService: nome del servizio
config.ws.target.cil.invioTelematicoSanita.serviceName=invioTelematicoSanitaService
#####  Servizio CIL InvioTelematicoSanitaService: endpoint del servizio
config.ws.target.cil.invioTelematicoSanita.serviceEndpoint=${config.ws.target.cil.invioTelematicoSanita.serviceEndpoint}
#####  Servizio CIL InvioTelematicoSanitaService: id della configurazione di Rampart (default se non utilizzato WS-Security)
config.ws.target.cil.invioTelematicoSanita.securityConfigId=default
#####  Servizio CIL InvioTelematicoSanitaService: path in cui salvare il file zip inviato al servizio (nessuna scrittura su disco se non specificato alcun valore)
config.ws.target.cil.invioTelematicoSanita.zip.save.path=${config.ws.target.cil.invioTelematicoSanita.zip.save.path}
#####  Servizio CIL InvioTelematicoSanitaService: overriding delle proprietà di configurazione del client
config.ws.target.cil.invioTelematicoSanita.customProp.config.ws.client.timeout=${config.ws.client.timeout}
config.ws.target.cil.invioTelematicoSanita.customProp.config.ws.client.so.timeout=${config.ws.client.so.timeout}

#####  Servizio CIL ElencoAnaliticoEsitoRicetteService: operation da richiamare
config.ws.target.cil.elencoAnaliticoEsitoRicette.operationName=visualizzaElencoStatoRicette
#####  Servizio CIL ElencoAnaliticoEsitoRicetteService: nome del servizio
config.ws.target.cil.elencoAnaliticoEsitoRicette.serviceName=ElencoAnaliticoEsitoRicetteService
#####  Servizio CIL ElencoAnaliticoEsitoRicetteService: endpoint del servizio
config.ws.target.cil.elencoAnaliticoEsitoRicette.serviceEndpoint=${config.ws.target.cil.elencoAnaliticoEsitoRicette.serviceEndpoint}
#####  Servizio CIL ElencoAnaliticoEsitoRicetteService: id della configurazione di Rampart (default se non utilizzato WS-Security)
config.ws.target.cil.elencoAnaliticoEsitoRicette.securityConfigId=default
#####  Servizio CIL ElencoAnaliticoEsitoRicetteService: overriding delle proprietà di configurazione del client
config.ws.target.cil.elencoAnaliticoEsitoRicette.customProp.config.ws.client.timeout=${config.ws.client.timeout}
config.ws.target.cil.elencoAnaliticoEsitoRicette.customProp.config.ws.client.so.timeout=${config.ws.client.so.timeout}

#####  Servizio CIL ElencoSinteticoStatoInviiService: operation da richiamare
config.ws.target.cil.elencoSinteticoStatoInvii.operationName=visualizzaElencoStatoInvii
#####  Servizio CIL ElencoSinteticoStatoInviiService: nome del servizio
config.ws.target.cil.elencoSinteticoStatoInvii.serviceName=ElencoSinteticoStatoInviiService
#####  Servizio CIL ElencoSinteticoStatoInviiService: endpoint del servizio
config.ws.target.cil.elencoSinteticoStatoInvii.serviceEndpoint=${config.ws.target.cil.elencoSinteticoStatoInvii.serviceEndpoint}
#####  Servizio CIL ElencoSinteticoStatoInviiService: id della configurazione di Rampart (default se non utilizzato WS-Security)
config.ws.target.cil.elencoSinteticoStatoInvii.securityConfigId=default
#####  Servizio CIL ElencoSinteticoStatoInviiService: overriding delle proprietà di configurazione del client
config.ws.target.cil.elencoSinteticoStatoInvii.customProp.config.ws.client.timeout=${config.ws.client.timeout}
config.ws.target.cil.elencoSinteticoStatoInvii.customProp.config.ws.client.so.timeout=${config.ws.client.so.timeout}

#####  Servizio CIL DemInterrogaNreUtilizzatiService: operation da richiamare
config.ws.target.cil.demInterrogaNreUtilizzati.operationName=interrogaNreUtilizzati
#####  Servizio CIL DemInterrogaNreUtilizzatiService: nome del servizio
config.ws.target.cil.demInterrogaNreUtilizzati.serviceName=demInterrogaNreUtilizzati
#####  Servizio CIL DemInterrogaNreUtilizzatiService: endpoint del servizio
config.ws.target.cil.demInterrogaNreUtilizzati.serviceEndpoint=${config.ws.target.cil.demInterrogaNreUtilizzati.serviceEndpoint}
#####  Servizio CIL DemInterrogaNreUtilizzatiService: id della configurazione di Rampart (default se non utilizzato WS-Security)
config.ws.target.cil.demInterrogaNreUtilizzati.securityConfigId=default
#####  Servizio CIL DemInterrogaNreUtilizzatiService: codice Istat regione Piemonte 
config.ws.target.cil.demInterrogaNreUtilizzati.codRegione=010
#####  Servizio CIL DemInterrogaNreUtilizzatiService: overriding delle proprietà di configurazione del client
config.ws.target.cil.demInterrogaNreUtilizzati.customProp.config.ws.client.timeout=${config.ws.client.timeout}
config.ws.target.cil.demInterrogaNreUtilizzati.customProp.config.ws.client.so.timeout=${config.ws.client.so.timeout}

#####  Servizio ePrescription: valore costante per SI, 1, YES, TRUE ecc.
config.ws.ePrescription.boolean.yes=S
#####  Servizio ePrescription: valore costante per NO, 0, FALSE ecc.
config.ws.ePrescription.boolean.no=N
#####  Servizio ePrescription: codici delle esenzioni per reddito
config.ws.ePrescription.list.esenzioniReddito=pippo,pluto,topolino
#####  Servizio ePrescription: valore da restituire al servizio in caso di esito negativo generico
config.ws.ePrescription.esito.negativo.code=9999
#####  Servizio ePrescription: valore da restituire al servizio in caso di esito positivo
config.ws.ePrescription.esito.positivo.code=0000
#####  Sovrascrive il valore passato in /ePrescription/medico/struttura se impostato un valore non nullo
config.ws.ePrescription.codiceAslAo.overwrite=
#####  Configurazione Servizio SAR per richiesta NRE
config.ws.target.sar.servizioRichiestaLotto.operationName=richiestaLotto
config.ws.target.sar.servizioRichiestaLotto.serviceName=nreRichiestaLottoPort
config.ws.target.sar.servizioRichiestaLotto.serviceEndpoint=${config.ws.target.sar.richiestaLotto.serviceEndpoint}
config.ws.target.sar.servizioRichiestaLotto.securityConfigId=default
config.ws.target.sar.legale.rappresentante=${config.ws.target.sar.rappresentante.legale}
config.ws.target.sar.cod.reg=${config.ws.target.sar.cod.reg}
config.ws.target.sar.cod.id.lotto=${config.ws.target.sar.cod.id.lotto}
config.ws.target.sar.pinCode=${config.ws.target.sar.pinCode}
#####  Valore di default per il codice della regione
config.ws.dem.default.codRegione=010

#Charset di default per le stringhe trattate dall'applicazione
config.default.charset=UTF-8

######  Soap version, supportate 1.0 o 1.1
config.ws.soap.version=1.1

##### Numero massimo di connessioni per host da tentare in parallelo su ognuno degli httpclient utilizzati
config.ws.client.max.connection.per.host=5

##### Numero massimo di connessioni gestite da ognuno degli httpclient utilizzait
config.ws.client.max.total.connection=25

##### Rilascio automatico delle connessioni
config.ws.client.auto.release.connection=true

##### Abilitazione utilizzo di HTTP chunked encoding true/false
config.ws.client.chunked.mode=false

######  Timeout per l'attesa di una connessione client axis2, espresso in millisecondi
config.ws.client.timeout=${config.ws.client.timeout}

##### Timeout del client in attesa di una risposta, espresso come millisecondi #####  
config.ws.client.so.timeout=${config.ws.client.so.timeout}

######  Path del repository dei moduli di axis2
config.ws.axis2.repository.path=/axis2-repository/

######  Path di axis2.xml
config.ws.axis2.config.path=/axis2-repository/conf/policy.client.axis2.xml

######  Path delle policy per l'interazione col servizio
config.ws.axis2.servicePolicy.path=/axis2-repository/conf/service.policy.xml

###### Confiugurazione valore attributo mustUnderstand in soap:Header
config.server.must.understand.headers=true

######  Configurazione properties di inizializzazione di Velocity
config.velocity.properties.resource.path=velocity.properties

config.axis2.client.http.auth.basic.username=${config.axis2.client.http.auth.basic.username}
config.axis2.client.http.auth.basic.password=${config.axis2.client.http.auth.basic.password}

######  Configurazione per integrazione su HTTP con TLS/SSL (nessun valore è letto se enabled=false)
config.ws.ssl.enabled=true
config.javax.net.ssl.trustStore=keystores/client-truststore.jks
config.javax.net.ssl.trustStorePassword=changeit
config.javax.net.ssl.trustStoreType=JKS
config.javax.net.ssl.keyStore=keystores/client-keystore.jks
config.javax.net.ssl.keyStorePassword=changeit
config.javax.net.ssl.keyStoreKeyPwd=changeit
config.javax.net.ssl.keyStoreType=JKS

#####  Configurazione proxy HTTP/HTTPS (nessun valore è letto se enabled=false)
config.ws.axis2.proxy.enabled=false
config.ws.axis2.proxy.nonProxyHosts="localhost"|"127.0.0.1"|"*"
config.ws.axis2.proxy.host=
config.ws.axis2.proxy.port=
config.ws.axis2.proxy.user=
config.ws.axis2.proxy.password=

#### Configurazione per la crittografia dei dati inviati dai client
config.crypto.rsa.encrypt.jks.file=keystores/client-keystore.jks
config.crypto.rsa.encrypt.jks.crt.alias=${config.crypto.rsa.encrypt.jks.crt.alias}
config.crypto.rsa.encrypt.jks.pwd=changeit

#### Servizi Reverse Proxy per Erogato
# config.ws.target.XXXX.http.auth.basic.override: se impostato a true viene fatto l'override dell'eventuale auth http basic già presente nel msg in ingresso
config.ws.target.annullaErogato.serviceEndpoint=${config.ws.target.annullaErogato.serviceEndpoint}
config.ws.target.annullaErogato.http.auth.basic.override=${config.ws.target.annullaErogato.http.auth.basic.override}
config.ws.target.invioErogato.serviceEndpoint=${config.ws.target.invioErogato.serviceEndpoint}
config.ws.target.invioErogato.http.auth.basic.override=${config.ws.target.invioErogato.http.auth.basic.override}
config.ws.target.sospendiErogato.serviceEndpoint=${config.ws.target.sospendiErogato.serviceEndpoint}
config.ws.target.sospendiErogato.http.auth.basic.override=${config.ws.target.sospendiErogato.http.auth.basic.override}
config.ws.target.visualizzaErogato.serviceEndpoint=${config.ws.target.visualizzaErogato.serviceEndpoint}
config.ws.target.visualizzaErogato.http.auth.basic.override=${config.ws.target.visualizzaErogato.http.auth.basic.override}
config.ws.target.db.vendor=${config.ws.target.db.vendor}
