CREATE TABLE SARP_MW.SP_LOTTINRE
(
  ID                 NUMBER,
  CF_RICHIEDENTE     VARCHAR2(255 BYTE),
  COD_LOTTO          VARCHAR2(4 BYTE)           NOT NULL,
  DT_INSERT          TIMESTAMP(0)               DEFAULT SYSDATE,
  TERMINATO          CHAR(1 BYTE)               DEFAULT 'F',
  DT_FINE            TIMESTAMP(0),
  COD_RAG_LOTTO      VARCHAR2(2 BYTE)           NOT NULL,
  COD_REGIONE_LOTTO  VARCHAR2(3 BYTE)           NOT NULL,
  COD_ID_LOTTO       VARCHAR2(4 BYTE)           NOT NULL
)
TABLESPACE ENGISAN_DATI
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SARP_MW.SP_LOTTINRE_PK ON SARP_MW.SP_LOTTINRE
(ID)
LOGGING
TABLESPACE ENGISAN_INDICI
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SARP_MW.SP_LOTTINRE ADD (
  CONSTRAINT SP_LOTTINRE_PK
  PRIMARY KEY
  (ID)
  USING INDEX SARP_MW.SP_LOTTINRE_PK
  ENABLE VALIDATE);

  
CREATE TABLE SARP_MW.SP_NRE
(
  ID_LOTTO         NUMBER,
  NRE_PROGRESSIVO  NUMBER,
  CF_MEDICO        VARCHAR2(16 BYTE),
  DT_INSERT        TIMESTAMP(0)                 DEFAULT sysdate,
  DT_ASSEGNAZIONE  TIMESTAMP(0)
)
TABLESPACE ENGISAN_DATI
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SARP_MW.SP_NRE_PK ON SARP_MW.SP_NRE
(ID_LOTTO, NRE_PROGRESSIVO)
LOGGING
TABLESPACE ENGISAN_INDICI
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SARP_MW.SP_NRE ADD (
  CONSTRAINT SP_NRE_PK
  PRIMARY KEY
  (ID_LOTTO, NRE_PROGRESSIVO)
  USING INDEX SARP_MW.SP_NRE_PK
  ENABLE VALIDATE);


CREATE TABLE SARP_MW.SP_TRANSACTION
(
  ID              NUMBER,
  CF_MEDICO       VARCHAR2(16 BYTE),
  CF_PAZIENTE     VARCHAR2(255 BYTE),
  NRE             VARCHAR2(30 BYTE),
  PROTOCOLLO_SAC  VARCHAR2(50 BYTE),
  DT_INSERT       TIMESTAMP(0)                  DEFAULT SYSDATE,
  MSG_MW_IN       BLOB,
  MSG_MW_SRV      BLOB,
  MSG_SRV_MW      BLOB,
  MSG_MW_OUT      BLOB,
  ESITO           VARCHAR2(100 BYTE),
  TIPO            VARCHAR2(100 BYTE)
)
LOB (MSG_MW_IN) STORE AS (
  TABLESPACE  ENGISAN_DATI
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
LOB (MSG_MW_SRV) STORE AS (
  TABLESPACE  ENGISAN_DATI
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
LOB (MSG_SRV_MW) STORE AS (
  TABLESPACE  ENGISAN_DATI
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
LOB (MSG_MW_OUT) STORE AS (
  TABLESPACE  ENGISAN_DATI
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE ENGISAN_DATI
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SARP_MW.SP_TRANSACTION_PK ON SARP_MW.SP_TRANSACTION
(ID)
LOGGING
TABLESPACE ENGISAN_INDICI
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SARP_MW.SP_TRANSACTION ADD (
  CONSTRAINT SP_TRANSACTION_PK
  PRIMARY KEY
  (ID)
  USING INDEX SARP_MW.SP_TRANSACTION_PK
  ENABLE VALIDATE);


CREATE TABLE SARP_MW.SP_TRANSACTION_ERROR
(
  ID           INTEGER,
  COD_ERROR    VARCHAR2(50 BYTE),
  DESCR_ERROR  VARCHAR2(255 BYTE),
  OPERATION    VARCHAR2(50 BYTE),
  DT_INSERT    TIMESTAMP(0)                     DEFAULT SYSDATE,
  ERROR_ORDER  NUMBER,
  TRANS_ID     NUMBER
)
TABLESPACE ENGISAN_DATI
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SARP_MW.SP_TRANSACTION_ERROR_PK ON SARP_MW.SP_TRANSACTION_ERROR
(ID)
LOGGING
TABLESPACE ENGISAN_INDICI
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SARP_MW.SP_TRANSACTION_ERROR ADD (
  CONSTRAINT SP_TRANSACTION_ERROR_PK
  PRIMARY KEY
  (ID)
  USING INDEX SARP_MW.SP_TRANSACTION_ERROR_PK
  ENABLE VALIDATE);
  
//##################################################################################################################


CREATE SEQUENCE SARP_MW.SEQ_LOTTO_PK
  START WITH 8
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;
  

CREATE SEQUENCE SARP_MW.SEQ_TRANS_ERR_PK
  START WITH 144
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE SEQUENCE SARP_MW.SEQ_TRANS_PK
  START WITH 149
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;