<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>it.eng.cct.dem.sar.piemonte.mw</groupId>
	<artifactId>sarpiemonte-mw-skeleton</artifactId>
	<version>1.0.1</version>
	<packaging>jar</packaging>
	<name>sarpiemonte-mw-skeleton</name>
	<url>http://www.eng.it</url>
	<parent>
		<groupId>it.eng.cct.dem.sar</groupId>
		<artifactId>sar-mw-base</artifactId>
		<version>1.0.0</version>
	</parent>
	<build>
		<resources>
			<resource>
				<directory>${project.build.directory}/generated-sources/axis2/wsdl2code/resources</directory>
				<includes>
					<include>**/**</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>xmlbeans-maven-plugin</artifactId>
				<version>2.3.3</version>
				<executions>
					<execution>
						<id>xsd2java</id>
						<goals>
							<goal>xmlbeans</goal>
						</goals>
						<phase>generate-sources</phase>
					</execution>
				</executions>
				<inherited>true</inherited>
				<configuration>
					<memoryInitialSize>128m</memoryInitialSize>
					<memoryMaximumSize>512m</memoryMaximumSize>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.axis2</groupId>
				<artifactId>axis2-wsdl2code-maven-plugin</artifactId>
				<version>1.6.2</version>
				<executions>
					<execution>
						<id>SarMiddlewareWSTrasmissione</id>
						<goals>
							<goal>wsdl2code</goal>
						</goals>
						<configuration>
							<wsdlFile>src/main/axis2/ePrescription.wsdl</wsdlFile>
							<serviceName>ePrescriptionService</serviceName>
							<portName>ePrescriptionPort</portName>
							<databindingName>xmlbeans</databindingName>
							<generateAllClasses>true</generateAllClasses>
							<generateServerSide>true</generateServerSide>
							<generateServerSideInterface>true</generateServerSideInterface>
							<generateServicesXml>false</generateServicesXml>
							<generateTestcase>true</generateTestcase>
							<language>java</language>
							<!-- <namespaceToPackages></namespaceToPackages> -->
							<namespaceURIs>
								<namespaceURI>
									<uri>http://cct.eng.it/dem/sar/piemonte/mw/schemas/</uri>
									<packageName>it.eng.cct.dem.sar.piemonte.mw.schemas</packageName>
								</namespaceURI>
							</namespaceURIs>
							<!-- <outputDirectory></outputDirectory> -->
							<packageName>it.eng.cct.dem.sar.piemonte.mw.schemas.SarMiddleware</packageName>
							<!-- <allPorts></allPorts> -->
							<!-- <syncMode>both</syncMode> -->
							<!-- <unpackClasses></unpackClasses> -->
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.apache.axis2</groupId>
										<artifactId>axis2-wsdl2code-maven-plugin</artifactId>
										<versionRange>[1.6.2,)</versionRange>
										<goals>
											<goal>wsdl2code</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.codehaus.mojo</groupId>
										<artifactId>xmlbeans-maven-plugin</artifactId>
										<versionRange>[2.3.3,)</versionRange>
										<goals>
											<goal>xmlbeans</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-kernel</artifactId>
			<version>1.6.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-xmlbeans</artifactId>
			<version>1.6.2</version>
		</dependency>
	</dependencies>
</project>
