config.ws.target.cil.richiestaNre.serviceEndpoint=http://localhost:8082/axis2/services/nreRequestService
config.ws.target.cil.demInvioPrescritto.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/DEM/Prescritto/InvioPrescritto
config.ws.target.cil.demAnnullaPrescritto.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/DEM/Prescritto/AnnullaPrescritto
config.ws.target.cil.demVisualizzaPrescritto.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/DEM/Prescritto/VisualizzaPrescritto
config.ws.target.cil.invioTelematicoSanita.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/REL/service/invioTelematicoSanita
config.ws.target.cil.elencoAnaliticoEsitoRicette.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/REL/service/elencoAnalitico
config.ws.target.cil.elencoSinteticoStatoInvii.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/REL/service/elencoSintetico
config.ws.target.cil.demInterrogaNreUtilizzati.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/DEM/Prescritto/InterrogaNreUtilizzati
config.ws.target.cil.invioTelematicoSanita.zip.save.path=/OLISAN/tomcat_inst22/zip

config.crypto.rsa.encrypt.jks.crt.alias=sirpe_prod

config.ws.client.timeout=180000
config.ws.client.so.timeout=10000

config.ws.target.cil.pinCode=

config.ws.target.cil.emulation=true

config.ws.service.monitoring=true
config.ws.service.monitoring.internalmsgs=false

config.axis2.client.http.auth.basic.username=SANDEMO42
config.axis2.client.http.auth.basic.password=SANITADEMO

config.ws.target.sar.richiestaLotto.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/REL/service/richiestaLotto
config.ws.target.sar.rappresentante.legale=PROVAX00X00X000Z
config.ws.target.sar.cod.reg=010
config.ws.target.sar.cod.id.lotto=3
config.ws.target.sar.pinCode=DEMOSAN$

config.ws.target.db.url=jdbc:oracle:thin:@192.168.200.201:1526:SODY
config.ws.target.db.dialect=org.hibernate.dialect.OracleDialect
config.ws.target.db.driverClass=oracle.jdbc.OracleDriver
config.ws.target.db.username=SARP_MW
config.ws.target.db.password=SARP_MW$2016
config.ws.target.db.showsql=true
config.ws.target.db.vendor=oracle

config.ws.target.sar.credential.db.load=true
##### indicare il kr_nome della si_keyrad (BASIC:37500000650 - PWD:37500000651)
config.ws.target.sar.credential.db.key.pinCode=PR_AZIENDA_PR_ELETTR|||PIN_CODE
config.ws.target.sar.credential.db.key.userName=PR_AZIENDA_PR_ELETTR|||USERNAME_BASIC_AUTH
config.ws.target.sar.credential.db.key.pwd=PR_AZIENDA_PR_ELETTR|||PASSWORD_BASIC_AUTH

config.ws.target.db.iride.url=jdbc:oracle:thin:@192.168.200.201:1526:SODY
config.ws.target.db.iride.dialect=org.hibernate.dialect.OracleDialect
config.ws.target.db.iride.driverClass=oracle.jdbc.OracleDriver
config.ws.target.db.iride.username=IRIDE
config.ws.target.db.iride.password=IRIDE
config.ws.target.db.iride.showsql=true

config.ws.target.annullaErogato.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/DEM/Erogato/AnnullaErogato
config.ws.target.annullaErogato.http.auth.basic.override=true
config.ws.target.invioErogato.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/DEM/Erogato/InvioErogato
config.ws.target.invioErogato.http.auth.basic.override=true
config.ws.target.sospendiErogato.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/DEM/Erogato/SospendiErogato
config.ws.target.sospendiErogato.http.auth.basic.override=true
config.ws.target.visualizzaErogato.serviceEndpoint=https://svc-sanita-internet.reteunitaria.piemonte.it/DEM/Erogato/VisualizzaErogato
config.ws.target.visualizzaErogato.http.auth.basic.override=true