config.ws.target.cil.richiestaNre.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Other/RichiestaNre
config.ws.target.cil.demInvioPrescritto.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Prescritto/InvioPrescritto
config.ws.target.cil.demAnnullaPrescritto.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Prescritto/AnnullaPrescritto
config.ws.target.cil.demVisualizzaPrescritto.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Prescritto/VisualizzaPrescritto
config.ws.target.cil.invioTelematicoSanita.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/RELCIL/service/invioTelematicoSanita
config.ws.target.cil.elencoAnaliticoEsitoRicette.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/RELCIL/service/elencoAnalitico
config.ws.target.cil.elencoSinteticoStatoInvii.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/RELCIL/service/elencoSintetico
config.ws.target.cil.demInterrogaNreUtilizzati.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Prescritto/InterrogaNreUtilizzati
config.ws.target.cil.invioTelematicoSanita.zip.save.path=

config.ws.client.timeout=180000
config.ws.client.so.timeout=10000

config.ws.target.cil.pinCode=12345678

config.ws.target.cil.emulation=false

config.ws.service.monitoring=false
config.ws.service.monitoring.internalmsgs=false

config.axis2.client.http.auth.basic.username=RE_ASL202_TO2
config.axis2.client.http.auth.basic.password=AAAAAAAA

config.ws.target.sar.richiestaLotto.serviceEndpoint=
config.ws.target.sar.rappresentante.legale=
config.ws.target.sar.cod.reg=010
config.ws.target.sar.cod.id.lotto=
config.ws.target.sar.pinCode=

config.ws.target.db.url=
config.ws.target.db.dialect=
config.ws.target.db.driverClass=
config.ws.target.db.username=
config.ws.target.db.password=
config.ws.target.db.showsql=
config.ws.target.db.vendor=

config.ws.target.sar.credential.db.load=true
config.ws.target.sar.credential.db.key.pinCode=
config.ws.target.sar.credential.db.key.userName=
config.ws.target.sar.credential.db.key.pwd=

config.ws.target.db.iride.url=
config.ws.target.db.iride.dialect=
config.ws.target.db.iride.driverClass=
config.ws.target.db.iride.username=
config.ws.target.db.iride.password=
config.ws.target.db.iride.showsql=

config.ws.target.annullaErogato.serviceEndpoint=
config.ws.target.annullaErogato.http.auth.basic.override=
config.ws.target.invioErogato.serviceEndpoint=
config.ws.target.invioErogato.http.auth.basic.override=
config.ws.target.sospendiErogato.serviceEndpoint=
config.ws.target.sospendiErogato.http.auth.basic.override=
config.ws.target.visualizzaErogato.serviceEndpoint=
config.ws.target.visualizzaErogato.http.auth.basic.override=