<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>it.eng.cct.dem.sar</groupId>
		<artifactId>sar-mw-base</artifactId>
		<version>1.0.0</version>
		<relativePath>../sar-mw-base</relativePath>
	</parent>
	<groupId>it.eng.cct.dem.sar</groupId>
	<artifactId>sar-piemonte-stub</artifactId>
	<version>1.0.0</version>
	<build>
		<resources>
			<resource>
				<directory>${project.build.directory}/generated-sources/axis2/wsdl2code/resources</directory>
				<includes>
					<include>**/**</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>xmlbeans-maven-plugin</artifactId>
				<version>2.3.3</version>
				<executions>
					<execution>
						<id>xsd2java</id>
						<goals>
							<goal>xmlbeans</goal>
						</goals>
						<phase>generate-sources</phase>
					</execution>
				</executions>
				<inherited>true</inherited>
				<configuration>
					<schemaDirectory>${basedir}/src/main/axis2/sistemaTiesse/dpcm260308/xsd</schemaDirectory>
					<memoryInitialSize>128m</memoryInitialSize>
					<memoryMaximumSize>512m</memoryMaximumSize>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.axis2</groupId>
				<artifactId>axis2-wsdl2code-maven-plugin</artifactId>
				<version>1.6.2</version>
				<executions>
					<execution>
						<id>SarRichiestaLottiNre</id>
						<goals>
							<goal>wsdl2code</goal>
						</goals>
						<configuration>
							<packageName>it.finanze.sanita.dem.dpcm.wsdl.richiestaLottiNre.service</packageName>
							<wsdlFile>src/main/resources/wsdl/richiestaLotto/lotto_wsdl.wsdl</wsdlFile>
							<databindingName>xmlbeans</databindingName>
							<unpackClasses>true</unpackClasses>
							<generateAllClasses>true</generateAllClasses>
							<generateServerSide>false</generateServerSide>
							<generateServicesXml>false</generateServicesXml>
							<generateServerSideInterface>false</generateServerSideInterface>
							<generateTestcase>true</generateTestcase>
							<language>java</language>
						</configuration>
					</execution>
					<execution>
						<id>SarInvioErogato</id>
						<goals>
							<goal>wsdl2code</goal>
						</goals>
						<configuration>
							<packageName>it.finanze.sanita.dem.dpcm.wsdl.invioErogato.service</packageName>
							<wsdlFile>src/main/resources/wsdl/invioErogato/InvioErogato.wsdl</wsdlFile>
							<databindingName>xmlbeans</databindingName>
							<unpackClasses>true</unpackClasses>
							<generateAllClasses>true</generateAllClasses>
							<generateServerSide>true</generateServerSide>
							<generateServicesXml>false</generateServicesXml>
							<generateServerSideInterface>false</generateServerSideInterface>
							<generateTestcase>true</generateTestcase>
							<language>java</language>
						</configuration>
					</execution>
					<execution>
						<id>SarVisualizzaErogato</id>
						<goals>
							<goal>wsdl2code</goal>
						</goals>
						<configuration>
							<packageName>it.finanze.sanita.dem.dpcm.wsdl.visualizzaErogato.service</packageName>
							<wsdlFile>src/main/resources/wsdl/visualizzaErogato/VisualizzaErogato.wsdl</wsdlFile>
							<databindingName>xmlbeans</databindingName>
							<unpackClasses>true</unpackClasses>
							<generateAllClasses>true</generateAllClasses>
							<generateServerSide>true</generateServerSide>
							<generateServicesXml>false</generateServicesXml>
							<generateServerSideInterface>false</generateServerSideInterface>
							<generateTestcase>true</generateTestcase>
							<language>java</language>
						</configuration>
					</execution>
					<execution>
						<id>SarAnnullaErogato</id>
						<goals>
							<goal>wsdl2code</goal>
						</goals>
						<configuration>
							<packageName>it.finanze.sanita.dem.dpcm.wsdl.annullaErogato.service</packageName>
							<wsdlFile>src/main/resources/wsdl/annullaErogato/AnnullaErogato.wsdl</wsdlFile>
							<databindingName>xmlbeans</databindingName>
							<unpackClasses>true</unpackClasses>
							<generateAllClasses>true</generateAllClasses>
							<generateServerSide>true</generateServerSide>
							<generateServicesXml>false</generateServicesXml>
							<generateServerSideInterface>false</generateServerSideInterface>
							<generateTestcase>true</generateTestcase>
							<language>java</language>
						</configuration>
					</execution>
					<execution>
						<id>SarSospendiErogato</id>
						<goals>
							<goal>wsdl2code</goal>
						</goals>
						<configuration>
							<packageName>it.finanze.sanita.dem.dpcm.wsdl.sospendiErogato.service</packageName>
							<wsdlFile>src/main/resources/wsdl/sospendiErogato/SospendiErogato.wsdl</wsdlFile>
							<databindingName>xmlbeans</databindingName>
							<unpackClasses>true</unpackClasses>
							<generateAllClasses>true</generateAllClasses>
							<generateServerSide>true</generateServerSide>
							<generateServicesXml>false</generateServicesXml>
							<generateServerSideInterface>false</generateServerSideInterface>
							<generateTestcase>true</generateTestcase>
							<language>java</language>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2</artifactId>
			<version>1.6.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
			<version>2.5.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.ws.commons.axiom</groupId>
			<artifactId>axiom-api</artifactId>
			<version>1.2.13</version>
		</dependency>
	</dependencies>
</project>