<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>it.eng.cct.dem.sar.piemonte</groupId>
	<artifactId>cil-mockservice</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>
	<name>cil-mockservice</name>
	<url>http://maven.apache.org</url>
	<parent>
		<groupId>it.eng.cct.dem.sar</groupId>
		<artifactId>sar-mw-base</artifactId>
		<version>1.0.0</version>
		<relativePath>../sar-mw-base</relativePath>
	</parent>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<it.eng.cct.aar.deploy.dir>F:/vcampa/projects/Engineering/piemonte/sar/apache-tomcat-6.0.37/webapps/axis2/WEB-INF/services</it.eng.cct.aar.deploy.dir>
	</properties>
	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.axis2</groupId>
				<artifactId>axis2-aar-maven-plugin</artifactId>
				<version>1.6.2</version>
				<configuration>
					<fileSets />
				</configuration>
				<executions>
					<execution>
						<id>PackagingAar</id>
						<goals>
							<goal>aar</goal>
						</goals>
						<phase>package</phase>
						<configuration>
							<primaryArtifact>false</primaryArtifact>
							<!--outputDirectory>${it.eng.cct.aar.deploy.dir}</outputDirectory -->
							<aarDirectory>${it.eng.cct.aar.deploy.dir}/${project.build.finalName}</aarDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>it.eng.cct.dem.sar.piemonte</groupId>
			<artifactId>cil-wsstubs</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.axis2</groupId>
			<artifactId>axis2-kernel</artifactId>
			<version>1.6.2</version>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>
	</dependencies>
</project>
