apiVersion: v1
data:
  APP_NAME: sar-mw-cil-service
  EUREKA_DEFAULT_ZONE: http://admin:admin@eureka-0.eureka.eureka.svc.cluster.local:8761/eureka
  HOST: svc-hl-sar-mw-cil-service.ellipse.svc.cluster.local
  JAVA_OPTS: -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8001
  METASPACE: 512m
  PORT: "8080"
  RMI_PORT: "9090"
  XMS: 1024m
  XMX: 3072m
kind: ConfigMap
metadata:
  name: cm-sar-mw-cil-env-prod
  namespace: ellipse
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8088"
    prometheus.io/scrape: "true"
  labels:
    app: sar-mw-cil-service
  name: svc-sar-mw-cil-prod
  namespace: ellipse
spec:
  clusterIP: ""
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prom
    port: 8088
    protocol: TCP
    targetPort: 8088
  - name: jmx
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: debug
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: sar-mw-cil
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sar-mw-cil
    microservice: integration
  name: sar-mw-cil-prod
  namespace: ellipse
spec:
  minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: sar-mw-cil
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sar-mw-cil
        deployment: sar-mw-cil
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cm-sar-mw-cil-env-prod
        image: registrysan.eng.it/healtheng/it.eng.cct.sar-mw-piemonte-axis2:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nc -z localhost 8080
          failureThreshold: 2
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: sar-mw-cil
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8001
          protocol: TCP
        - containerPort: 8088
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nc -z localhost 8080
          failureThreshold: 2
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 2
            memory: 3G
          requests:
            cpu: 1
            memory: 1G
        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nc -z localhost 8080
          failureThreshold: 2
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
      imagePullSecrets:
      - name: registrysan
