config.ws.target.cil.richiestaNre.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Other/RichiestaNre
config.ws.target.cil.demInvioPrescritto.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Prescritto/InvioPrescritto
config.ws.target.cil.demAnnullaPrescritto.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Prescritto/AnnullaPrescritto
config.ws.target.cil.demVisualizzaPrescritto.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Prescritto/VisualizzaPrescritto
config.ws.target.cil.invioTelematicoSanita.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/RELCIL/service/invioTelematicoSanita
config.ws.target.cil.elencoAnaliticoEsitoRicette.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/RELCIL/service/elencoAnalitico
config.ws.target.cil.elencoSinteticoStatoInvii.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/RELCIL/service/elencoSintetico
config.ws.target.cil.demInterrogaNreUtilizzati.serviceEndpoint=https://tst-applogic.reteunitaria.piemonte.it:1449/DEMCIL/Prescritto/InterrogaNreUtilizzati
config.ws.target.cil.invioTelematicoSanita.zip.save.path=/engi/axis2/invii

config.ws.client.timeout=180000
config.ws.client.so.timeout=10000

config.ws.target.cil.pinCode=12345678

config.axis2.client.http.auth.basic.username=RE_ASL202_TO2
config.axis2.client.http.auth.basic.password=AAAAAAAA

######  Configurazione per integrazione su HTTP con TLS/SSL (nessun valore è letto se enabled=false)
config.ws.ssl.enabled=true
config.javax.net.ssl.trustStore=keystores/client-truststore.jks
config.javax.net.ssl.trustStorePassword=changeit
config.javax.net.ssl.trustStoreType=JKS
config.javax.net.ssl.keyStore=keystores/client-keystore.jks
config.javax.net.ssl.keyStorePassword=changeit
config.javax.net.ssl.keyStoreKeyPwd=changeit
config.javax.net.ssl.keyStoreType=JKS