config.ws.target.cil.richiestaNre.serviceEndpoint=https://asl207bi.isan.csi.it/cil/DEM/Other/RichiestaNre
config.ws.target.cil.demInvioPrescritto.serviceEndpoint=https://asl207bi.isan.csi.it/cil/DEM/Prescritto/InvioPrescritto
config.ws.target.cil.demAnnullaPrescritto.serviceEndpoint=https://asl207bi.isan.csi.it/cil/DEM/Prescritto/AnnullaPrescritto
config.ws.target.cil.demVisualizzaPrescritto.serviceEndpoint=https://asl207bi.isan.csi.it/cil/DEM/Prescritto/VisualizzaPrescritto
config.ws.target.cil.invioTelematicoSanita.serviceEndpoint=https://asl207bi.isan.csi.it/cil/REL/service/invioTelematicoSanita
config.ws.target.cil.elencoAnaliticoEsitoRicette.serviceEndpoint=https://asl207bi.isan.csi.it/cil/REL/service/elencoAnalitico
config.ws.target.cil.elencoSinteticoStatoInvii.serviceEndpoint=https://asl207bi.isan.csi.it/cil/REL/service/elencoSintetico
config.ws.target.cil.demInterrogaNreUtilizzati.serviceEndpoint=https://asl207bi.isan.csi.it/cil/DEM/Prescritto/InterrogaNreUtilizzati
config.ws.target.cil.invioTelematicoSanita.zip.save.path=


config.ws.client.timeout=180000
config.ws.client.so.timeout=10000

config.ws.target.cil.pinCode=207SGP02

config.axis2.client.http.auth.basic.username=ASR207CIL02
config.axis2.client.http.auth.basic.password=2DG7356HZ9W6TCZS


######  Configurazione per integrazione su HTTP con TLS/SSL (nessun valore \uFFFD letto se enabled=false)
#truststore, vengono usati
config.ws.ssl.enabled=true
config.javax.net.ssl.trustStore=keystores/client-truststore-aslbi_live.jks
config.javax.net.ssl.trustStorePassword=12345678
config.javax.net.ssl.trustStoreType=JKS
#I seguenti 4 parametri non vengono utilizzati, ma bisogna mettere un file esistente se no da errore
config.javax.net.ssl.keyStore=keystores/client-truststore-aslbi_live.jks
config.javax.net.ssl.keyStorePassword=12345678
config.javax.net.ssl.keyStoreKeyPwd=12345678
config.javax.net.ssl.keyStoreType=JKS
