config.ws.target.cil.richiestaNre.serviceEndpoint=https://aso905magg.isan.csi.it/cil/DEM/Other/RichiestaNre
config.ws.target.cil.demInvioPrescritto.serviceEndpoint=https://aso905magg.isan.csi.it/cil/DEM/Prescritto/InvioPrescritto
config.ws.target.cil.demAnnullaPrescritto.serviceEndpoint=https://aso905magg.isan.csi.it/cil/DEM/Prescritto/AnnullaPrescritto
config.ws.target.cil.demVisualizzaPrescritto.serviceEndpoint=https://aso905magg.isan.csi.it/cil/DEM/Prescritto/VisualizzaPrescritto
config.ws.target.cil.invioTelematicoSanita.serviceEndpoint=https://aso905magg.isan.csi.it/cil/REL/service/invioTelematicoSanita
config.ws.target.cil.elencoAnaliticoEsitoRicette.serviceEndpoint=https://aso905magg.isan.csi.it/cil/REL/service/elencoAnalitico
config.ws.target.cil.elencoSinteticoStatoInvii.serviceEndpoint=https://aso905magg.isan.csi.it/cil/REL/service/elencoSintetico
config.ws.target.cil.demInterrogaNreUtilizzati.serviceEndpoint=https://aso905magg.isan.csi.it/cil/DEM/Prescritto/InterrogaNreUtilizzati
config.ws.target.cil.invioTelematicoSanita.zip.save.path=/U01/invii_DPCM

config.ws.client.timeout=180000
config.ws.client.so.timeout=10000

config.ws.target.cil.pinCode=905COP03

config.axis2.client.http.auth.basic.username=ASO905CIL3
config.axis2.client.http.auth.basic.password=66269SS5W5T4D468

######  Configurazione per integrazione su HTTP con TLS/SSL (nessun valore è letto se enabled=false)
config.ws.ssl.enabled=true
config.javax.net.ssl.trustStore=keystores/client-truststore_novaraaso_live.jks
config.javax.net.ssl.trustStorePassword=trustnovara
config.javax.net.ssl.trustStoreType=JKS
config.javax.net.ssl.keyStore=keystores/client-truststore_novaraaso_live.jks
config.javax.net.ssl.keyStorePassword=trustnovara
config.javax.net.ssl.keyStoreKeyPwd=trustnovara
config.javax.net.ssl.keyStoreType=JKS