<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>it.eng.cct.dem.sar.piemonte</groupId>
	<artifactId>sar-middleware</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>
	<name>sar-middleware</name>
	<url>http://maven.apache.org</url>
	<parent>
		<groupId>it.eng.cct.dem.sar</groupId>
		<artifactId>sar-mw-base</artifactId>
		<version>1.0.0</version>
		<relativePath>../sar-mw-base</relativePath>
	</parent>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<it.eng.cct.deploy.env>dev</it.eng.cct.deploy.env>
		<it.eng.cct.aar.deploy.dir>${project.build.directory}</it.eng.cct.aar.deploy.dir>
	</properties>
	<build>
		<filters>
			<filter>src/main/filters/filter-${it.eng.cct.deploy.env}.properties</filter>
		</filters>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.axis2</groupId>
				<artifactId>axis2-aar-maven-plugin</artifactId>
				<version>1.6.2</version>
				<configuration>
					<fileSets />
				</configuration>
				<executions>
					<execution>
						<id>PackagingAar</id>
						<goals>
							<goal>aar</goal>
						</goals>
						<phase>package</phase>
						<configuration>
							<primaryArtifact>false</primaryArtifact>
							<aarDirectory>${it.eng.cct.aar.deploy.dir}/${project.build.finalName}</aarDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>it.eng.cct.dem.sar.piemonte</groupId>
			<artifactId>sar-mw-piemonte</artifactId>
			<version>1.0.1</version>
			<type>jar</type>
			<exclusions>
				<exclusion>
					<artifactId>servlet-api</artifactId>
					<groupId>javax.servlet</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>it.eng.cct.dem.sar.piemonte</groupId>
			<artifactId>cil-wsstubs</artifactId>
			<version>1.0.1</version>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>dev</id>
			<properties>
				<it.eng.cct.deploy.env>dev</it.eng.cct.deploy.env>
				<it.eng.cct.aar.deploy.dir>${project.build.directory}</it.eng.cct.aar.deploy.dir>
			</properties>
		</profile>
		<profile>
			<id>live</id>
			<properties>
				<it.eng.cct.deploy.env>live</it.eng.cct.deploy.env>
			</properties>
		</profile>
		<profile>
			<id>aslto2_live</id>
			<properties>
				<it.eng.cct.deploy.env>aslto2_live</it.eng.cct.deploy.env>
			</properties>
		</profile>
		<profile>
			<id>aslto1_live</id>
			<properties>
				<it.eng.cct.deploy.env>aslto1_live</it.eng.cct.deploy.env>
			</properties>
		</profile>
		<profile>
			<id>aslto4_live</id>
			<properties>
				<it.eng.cct.deploy.env>aslto4_live</it.eng.cct.deploy.env>
			</properties>
		</profile>
		<profile>
			<id>aslto4_test</id>
			<properties>
				<it.eng.cct.deploy.env>aslto4_test</it.eng.cct.deploy.env>
			</properties>
		</profile>
		<profile>
			<id>orba_live</id>
			<properties>
				<it.eng.cct.deploy.env>orba_live</it.eng.cct.deploy.env>
			</properties>
		</profile>
		<profile>
			<id>aslvco_live</id>
			<properties>
				<it.eng.cct.deploy.env>aslvco_live</it.eng.cct.deploy.env>
			</properties>
		</profile>
		<profile>
			<id>aslbi_live</id>
			<properties>
				<it.eng.cct.deploy.env>aslbi_live</it.eng.cct.deploy.env>
			</properties>
		</profile>
		<profile>
			<id>novara</id>
			<properties>
				<it.eng.cct.deploy.env>novara_live</it.eng.cct.deploy.env>
			</properties>
		</profile>
		<profile>
			<id>test</id>
			<properties>
				<it.eng.cct.deploy.env>test</it.eng.cct.deploy.env>
			</properties>
		</profile>
	</profiles>
</project>
